trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - Portal_Routes/*
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none
- script: echo "Trigger Routes!"