trigger:
  branches:
    include:
    - releases/*
    - main
  paths:
    include:
      - '*'
    exclude:
    - Portal_Routes
    - azure-pipelines.yml
    - web-app-routes.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none
- script: echo "Trigger Main Repo!"