trigger:
  branches:
    include:
    - releases/*
    - main

pr:
  branches:
    include:
      - main
  drafts: false

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: isPR
  value: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
- checkout: none
- script: echo "$(isPR)"